--- #YAML:1.0
name:               App-Test-Tapat
version:            0.04
abstract:           An automated testing framework
author:
    - Jeremiah C. Foster <jeremiah@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Moose:                0
    TAP::Harness:         0
    TAP::Parser:          0
    TAP::Parser::Aggregator:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
